services:

  bot:
    image: moneyspentbot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT}:${DB_PORT}
    volumes:
     - ./postgres:/data/postgres
     - ./moneyspent.sql:/docker-entrypoint-initdb.d/moneyspent.sql